version: "3.9"
services:
  activemq:
    image: rmohr/activemq
    ports:
      - "61616:61616"
      - "8161:8161"

  platerec:
    build: 
      context: .
      dockerfile: Dockerfile

  testHarness:
    build: 
      context: .
      dockerfile:     