# Debian linux openjdk Tomcat official release
# startup script included
# https://hub.docker.com/_/tomcat?tab=description&page=1&ordering=last_updated

FROM tomcat:9.0.41-jdk11-openjdk
# copy war into image
COPY /target/docker/userinterface-web-0.1-SNAPSHOT.war /usr/local/tomcat/webapps/userinterface-web-0.1-SNAPSHOT.war 






