#set( $symbol_pound = '#' )
#set( $symbol_dollar = '$' )
#set( $symbol_escape = '\' )
/*
 * Service Problem Management
 * ${symbol_pound}${symbol_pound} TMF API Reference: ${tmfSpecPackageName} - Service Problem Management  ${symbol_pound}${symbol_pound}${symbol_pound} Release : 18.5 - December 2018  Service Problem Management API goal is to provide the ability to manage problems in the Service domain.   ${symbol_pound}${symbol_pound}${symbol_pound} Resource  - serviceProblem  ${symbol_pound}${symbol_pound}${symbol_pound} Operations Service Problem Management API performs the following operations on the resource : - Retrieve an entity or a collection of entities depending on filter criteria - Partial update of an entity (including updating rules) - Create an entity (including default values and creation rules) - Delete an entity (for administration purposes) - Manage notification of events
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.opennms.tmforum.tmf650.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import javax.validation.constraints.*;

/**
 * Sets the communication endpoint address the service instance must use to deliver notification information
 */
@ApiModel(description = "Sets the communication endpoint address the service instance must use to deliver notification information")
public class GenericEventSubscription   {
    
  @JsonProperty("id")
  private String id = null;

  @JsonProperty("callback")
  private String callback = null;

  @JsonProperty("query")
  private String query = null;

  public GenericEventSubscription id(String id) {
    this.id = id;
    return this;
  }

  /**
   * Id of the listener
   * @return id
   **/
  @JsonProperty("id")
  @ApiModelProperty(required = true, value = "Id of the listener")
  @NotNull
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public GenericEventSubscription callback(String callback) {
    this.callback = callback;
    return this;
  }

  /**
   * The callback being registered.
   * @return callback
   **/
  @JsonProperty("callback")
  @ApiModelProperty(required = true, value = "The callback being registered.")
  @NotNull
  public String getCallback() {
    return callback;
  }

  public void setCallback(String callback) {
    this.callback = callback;
  }

  public GenericEventSubscription query(String query) {
    this.query = query;
    return this;
  }

  /**
   * additional data to be passed
   * @return query
   **/
  @JsonProperty("query")
  @ApiModelProperty(value = "additional data to be passed")
  public String getQuery() {
    return query;
  }

  public void setQuery(String query) {
    this.query = query;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GenericEventSubscription genericEventSubscription = (GenericEventSubscription) o;
    return Objects.equals(this.id, genericEventSubscription.id) &&
        Objects.equals(this.callback, genericEventSubscription.callback) &&
        Objects.equals(this.query, genericEventSubscription.query);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, callback, query);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EventSubscription {${symbol_escape}n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("${symbol_escape}n");
    sb.append("    callback: ").append(toIndentedString(callback)).append("${symbol_escape}n");
    sb.append("    query: ").append(toIndentedString(query)).append("${symbol_escape}n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("${symbol_escape}n", "${symbol_escape}n    ");
  }
}

